try:
    import megatron.bridge  # noqa: F401

    HAVE_MEGATRON_BRIDGE = True
except ModuleNotFoundError:
    HAVE_MEGATRON_BRIDGE = False

if HAVE_MEGATRON_BRIDGE:
    from .deepseek_llm_pretrain import (
        deepseek_v3_pretrain_config_b200,
        deepseek_v3_pretrain_config_b300,
        deepseek_v3_pretrain_config_gb200,
        deepseek_v3_pretrain_config_gb300,
        deepseek_v3_pretrain_config_h100,
    )

from .deepseek_workload_base_configs import (
    DEEPSEEK_V3_PRETRAIN_CONFIG_B200_BF16,
    DEEPSEEK_V3_PRETRAIN_CONFIG_B200_FP8_CS,
    DEEPSEEK_V3_PRETRAIN_CONFIG_B200_FP8_MX,
    DEEPSEEK_V3_PRETRAIN_CONFIG_B300_BF16,
    DEEPSEEK_V3_PRETRAIN_CONFIG_B300_FP8_CS,
    DEEPSEEK_V3_PRETRAIN_CONFIG_B300_FP8_MX,
    DEEPSEEK_V3_PRETRAIN_CONFIG_GB200_BF16,
    DEEPSEEK_V3_PRETRAIN_CONFIG_GB200_FP8_CS,
    DEEPSEEK_V3_PRETRAIN_CONFIG_GB200_FP8_MX,
    DEEPSEEK_V3_PRETRAIN_CONFIG_GB300_BF16,
    DEEPSEEK_V3_PRETRAIN_CONFIG_GB300_FP8_CS,
    DEEPSEEK_V3_PRETRAIN_CONFIG_GB300_FP8_MX,
    DEEPSEEK_V3_PRETRAIN_CONFIG_GB300_NVFP4,
    DEEPSEEK_V3_PRETRAIN_CONFIG_H100_BF16,
    DEEPSEEK_V3_PRETRAIN_CONFIG_H100_FP8_CS,
    DEEPSEEK_V3_PRETRAIN_CONFIG_H100_FP8_SC,
)


__all__ = [
    "DEEPSEEK_V3_PRETRAIN_CONFIG_B300_BF16",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_B300_FP8_CS",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_B300_FP8_MX",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_B200_BF16",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_B200_FP8_CS",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_B200_FP8_MX",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_GB200_BF16",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_GB200_FP8_CS",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_GB200_FP8_MX",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_GB300_BF16",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_GB300_FP8_CS",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_GB300_FP8_MX",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_GB300_NVFP4",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_H100_BF16",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_H100_FP8_CS",
    "DEEPSEEK_V3_PRETRAIN_CONFIG_H100_FP8_SC",
]

if HAVE_MEGATRON_BRIDGE:
    __all__.extend(
        [
            "deepseek_v3_pretrain_config_gb300",
            "deepseek_v3_pretrain_config_gb200",
            "deepseek_v3_pretrain_config_b300",
            "deepseek_v3_pretrain_config_b200",
            "deepseek_v3_pretrain_config_h100",
        ]
    )
